import type { Metadata } from "next";
import Link from "next/link";
import { notFound, permanentRedirect } from "next/navigation";
import { getArticleBySlug, getRelatedArticles } from "@/lib/articles";
import { categoryLabel, categorySlug } from "@/lib/categories";
import { estimateReadMinutes, formatDate } from "@/lib/format";
import { SITE_NAME } from "@/lib/site";
import { articleUrl, breadcrumbJsonLd, jsonLdString, newsArticleJsonLd } from "@/lib/seo";
import ArticleCard from "@/components/ArticleCard";
import SectionHeading from "@/components/SectionHeading";
import ShareButtons from "@/components/ShareButtons";
import BookmarkButton from "@/components/BookmarkButton";
import ReadingProgressBar from "@/components/ReadingProgressBar";
import FontSizeControl from "@/components/FontSizeControl";

export const revalidate = 300;

export async function generateMetadata({
  params,
}: {
  params: Promise<{ category: string; slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const article = await getArticleBySlug(slug);
  if (!article) return {};

  const url = articleUrl(article);
  const description = article.meta_description ?? undefined;

  return {
    title: article.title,
    description,
    keywords: article.tags ?? undefined,
    authors: [{ name: `${SITE_NAME} Editorial Team` }],
    alternates: { canonical: url },
    openGraph: {
      title: article.title,
      description,
      url,
      type: "article",
      siteName: SITE_NAME,
      locale: "en_US",
      publishedTime: article.published_at ?? undefined,
      section: categoryLabel(article.category),
      tags: article.tags ?? undefined,
    },
    twitter: {
      card: "summary",
      title: article.title,
      description,
    },
  };
}

export default async function ArticlePage({
  params,
}: {
  params: Promise<{ category: string; slug: string }>;
}) {
  const { category, slug } = await params;

  const article = await getArticleBySlug(slug);
  if (!article) notFound();

  // One canonical URL per article: a stale/wrong category segment 301s to the real one.
  const realCategory = categorySlug(article.category);
  if (category !== realCategory) {
    permanentRedirect(`/${realCategory}/${article.slug}`);
  }

  const label = categoryLabel(article.category);
  const url = articleUrl(article);
  const readMinutes = estimateReadMinutes(article.body);

  const related = await getRelatedArticles(article.category, article.id, 4);

  return (
    <div className="mx-auto max-w-3xl px-4 py-10">
      <ReadingProgressBar />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdString(newsArticleJsonLd(article)) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLdString(breadcrumbJsonLd(article)) }}
      />

      <article>
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-ink-muted">
          <Link href="/" className="hover:text-breaking hover:underline">Home</Link>
          <span aria-hidden="true">›</span>
          <Link href={`/${realCategory}`} className="font-extrabold text-breaking hover:underline">
            {label}
          </Link>
        </nav>

        <div className="mt-3 flex items-start justify-between gap-3">
          <h1 className="headline-display text-4xl font-extrabold leading-tight text-ink sm:text-5xl">
            {article.title}
          </h1>
          <BookmarkButton article={article} label="Save" className="mt-2 text-ink-muted hover:text-breaking" />
        </div>

        {article.meta_description && (
          <p className="article-summary mt-4 text-lg font-medium leading-snug text-ink-muted">
            {article.meta_description}
          </p>
        )}

        <div className="mt-4 flex flex-wrap items-center justify-between gap-x-3 gap-y-2 border-y border-line py-2.5">
          <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs font-semibold uppercase tracking-wide text-ink-muted">
            <span>{SITE_NAME} Editorial Team</span>
            <span aria-hidden="true">·</span>
            <time dateTime={article.published_at ?? undefined}>
              Published {formatDate(article.published_at)}
            </time>
            <span aria-hidden="true">·</span>
            <span>{readMinutes} min read</span>
          </div>
          <FontSizeControl label="Text size" />
        </div>

        <div
          className="prose-article mt-6 leading-relaxed text-ink [&_a]:text-brand [&_a]:underline [&_h2]:headline-en [&_h2]:mt-6 [&_h2]:text-xl [&_h2]:font-bold"
          // Body HTML is generated by our own backend pipeline, not user input.
          dangerouslySetInnerHTML={{ __html: article.body }}
        />

        {article.tags && article.tags.length > 0 && (
          <div className="mt-6 flex flex-wrap gap-2">
            {article.tags.map((tag) => (
              <Link
                key={tag}
                href={`/tag/${encodeURIComponent(tag)}`}
                className="border border-line px-2 py-0.5 text-xs text-ink-muted hover:border-breaking hover:text-breaking"
              >
                #{tag}
              </Link>
            ))}
          </div>
        )}

        {article.source_attribution && (
          <p className="mt-6 border-s-4 border-line ps-3 text-sm italic text-ink-muted">
            Source: {article.source_attribution}
          </p>
        )}

        <div className="mt-6">
          <ShareButtons url={url} title={article.title} />
        </div>
      </article>

      {related.length > 0 && (
        <section className="mt-14">
          <SectionHeading>Related Stories</SectionHeading>
          <div className="mt-5 grid gap-5 sm:grid-cols-2">
            {related.map((item) => (
              <ArticleCard key={item.id} article={item} variant="default" />
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
